### ISSUE TITLE
Npm start fails

### ISSUE THREAD

**Issue by rubensworks** [julianrojas87/IMEC_Labs_App#1]
Hi Julian,

I was trying out your application, but I can seem to get it working on my machine when executing `npm start`.
Could you help me with getting this running?

```
> imec-app@1.0.0 start /Users/rtaelman/Downloads/IMEC_Labs_App
> node server.js


/Users/rtaelman/Downloads/IMEC_Labs_App/node_modules/mongodb/lib/server.js:265
        process.nextTick(function() { throw err; })
                                      ^
MongoError: failed to connect to server [localhost:27017] on first connect
    at Pool.<anonymous> (/Users/rtaelman/Downloads/IMEC_Labs_App/node_modules/mongodb-core/lib/topologies/server.js:325:35)
    at emitOne (events.js:96:13)
    at Pool.emit (events.js:188:7)
    at Connection.<anonymous> (/Users/rtaelman/Downloads/IMEC_Labs_App/node_modules/mongodb-core/lib/connection/pool.js:270:12)
    at Connection.g (events.js:291:16)
    at emitTwo (events.js:106:13)
    at Connection.emit (events.js:191:7)
    at Socket.<anonymous> (/Users/rtaelman/Downloads/IMEC_Labs_App/node_modules/mongodb-core/lib/connection/connection.js:173:49)
    at Socket.g (events.js:291:16)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1276:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.8.1
npm ERR! npm  v3.6.0
npm ERR! code ELIFECYCLE
npm ERR! imec-app@1.0.0 start: `node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the imec-app@1.0.0 start script 'node server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the imec-app package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs imec-app
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls imec-app
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/rtaelman/Downloads/IMEC_Labs_App/npm-debug.log
```

I also tried removing your included `node_modules` and running `npm install` myself, but this did not solve the problem.

**Comment by julianrojas87** [comment]
Hi Ruben,

Looking at the error you are getting it seems that your MongoDB is either not running or bound to a different IP. Please try the following to make sure it is up and running:

```bash
$ sudo service mongod start
```
Also verify the IP to which is bound on the following file (location on my machine):

```bash
$ gedit /etc/mongod.conf
```
network interfaces
net:
  port: 27017
  bindIp: 127.0.0.1

Make sure it is bound to the localhost IP and the port 27017.
On the following link is a copy of the application that I am sure works properly. Try running this one and if you still have issues it must be related to your DB configuration:

https://drive.google.com/open?id=0B7GvlbEyZIu1NUZ5aDFzN3pFanM

Please let me know how it goes.

Thank you.

**Comment by rubensworks** [comment]
Hi Julian,

Thanks for you quick reply.
I wasn't aware of the additional requirement to have a running MongoDB instance.
After setting this up, your application starts and everything seems to be working as intended.

Thanks for your help!

**Comment by julianrojas87** [comment]
Hi Ruben,

That is good to hear. Please let me know if I can assist you with anything else.

Best regards!
